services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy_headers.conf:/etc/nginx/proxy_headers.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      - nginx-proxy_network

networks:
  nginx-proxy_network:
    external: true